# Generated by Django 3.2.7 on 2021-09-17 12:57

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import post.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_oz', models.CharField(max_length=255, null=True)),
                ('title_qr', models.CharField(max_length=255, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, null=True, populate_from=post.models.Post.get_populate, unique=True)),
                ('content', models.TextField()),
                ('content_uz', models.TextField(null=True)),
                ('content_ru', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('content_oz', models.TextField(null=True)),
                ('content_qr', models.TextField(null=True)),
                ('short_content', models.TextField(blank=True, null=True)),
                ('short_content_uz', models.TextField(blank=True, null=True)),
                ('short_content_ru', models.TextField(blank=True, null=True)),
                ('short_content_en', models.TextField(blank=True, null=True)),
                ('short_content_oz', models.TextField(blank=True, null=True)),
                ('short_content_qr', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('views', models.PositiveIntegerField(default=0)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('on_slider', models.BooleanField(default=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', to='menu.menu')),
            ],
            options={
                'ordering': ['position', '-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('title_uz', models.CharField(max_length=128, null=True)),
                ('title_ru', models.CharField(max_length=128, null=True)),
                ('title_en', models.CharField(max_length=128, null=True)),
                ('title_oz', models.CharField(max_length=128, null=True)),
                ('title_qr', models.CharField(max_length=128, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=150, null=True, populate_from=post.models.Tag.get_populate, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(upload_to='post_images/')),
                ('is_active', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='post.post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='post_attachments/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='post.post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='post.Tag'),
        ),
    ]
