# Generated by Django 3.2.7 on 2021-09-30 14:42

import autoslug.fields
from django.db import migrations
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=255, null=True, populate_from=post.models.Post.get_populate, unique=True),
        ),
    ]
