# Generated by Django 3.2.7 on 2021-10-18 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0016_auto_20211018_1743'),
        ('menu', '0002_auto_20210929_1221'),
        ('post', '0005_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['position', '-pub_date']},
        ),
        migrations.AddField(
            model_name='post',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='structure.organization'),
        ),
        migrations.AlterField(
            model_name='post',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='menu.menu'),
        ),
    ]
