# Generated by Django 3.2.7 on 2021-10-18 14:33

import autoslug.fields
from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20211018_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=500, null=True, populate_from=post.models.Post.get_populate, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_oz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_qr',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_uz',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
