# Generated by Django 3.2.7 on 2021-10-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_innovation_territory'),
    ]

    operations = [
        migrations.AddField(
            model_name='postattachment',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='postattachment',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='postattachment',
            name='title_oz',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='postattachment',
            name='title_qr',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='postattachment',
            name='title_ru',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='postattachment',
            name='title_uz',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
