# Generated by Django 3.2.7 on 2021-11-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20211102_1356'),
        ('post', '0010_post_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='menu',
        ),
        migrations.AddField(
            model_name='post',
            name='menu',
            field=models.ManyToManyField(blank=True, null=True, related_name='posts', to='menu.Menu'),
        ),
    ]
