# Generated by Django 3.2.7 on 2021-11-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_post_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
