# Generated by Django 3.2.7 on 2021-11-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_alter_post_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='postimage',
            name='order',
            field=models.SmallIntegerField(default=1),
        ),
    ]
