# Generated by Django 3.2.7 on 2021-11-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20211112_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contest_type',
            field=models.SmallIntegerField(choices=[('1', 'Practical'), ('2', 'Fundamental'), ('3', 'Innovation'), ('4', 'Startup'), ('5', 'Cooperation')], default=1),
            preserve_default=False,
        ),
    ]
