# Generated by Django 3.2.7 on 2021-11-29 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_auto_20211127_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date', 'position']},
        ),
    ]
