# Generated by Django 3.2.7 on 2021-11-30 10:51

import autoslug.fields
from django.db import migrations
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, max_length=500, null=True, populate_from=post.models.Post.get_populate, unique=True),
        ),
    ]
