# Generated by Django 3.2.7 on 2022-01-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_alter_post_contest_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_oz', models.CharField(max_length=255, null=True)),
                ('title_qr', models.CharField(max_length=255, null=True)),
                ('url', models.URLField()),
                ('position', models.SmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['position', '-created_at'],
            },
        ),
    ]
