# Generated by Django 3.2.7 on 2021-10-07 06:46

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import structure.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0008_alter_interactiveservice_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_oz', models.CharField(max_length=255, null=True)),
                ('title_qr', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('address_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('address_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('address_en', models.CharField(blank=True, max_length=255, null=True)),
                ('address_oz', models.CharField(blank=True, max_length=255, null=True)),
                ('address_qr', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=100)),
                ('full_name_uz', models.CharField(max_length=100, null=True)),
                ('full_name_ru', models.CharField(max_length=100, null=True)),
                ('full_name_en', models.CharField(max_length=100, null=True)),
                ('full_name_oz', models.CharField(max_length=100, null=True)),
                ('full_name_qr', models.CharField(max_length=100, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=150, populate_from=structure.models.Staff.get_populate, unique=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('biography_uz', models.TextField(blank=True, null=True)),
                ('biography_ru', models.TextField(blank=True, null=True)),
                ('biography_en', models.TextField(blank=True, null=True)),
                ('biography_oz', models.TextField(blank=True, null=True)),
                ('biography_qr', models.TextField(blank=True, null=True)),
                ('obligation', models.TextField(blank=True, null=True)),
                ('obligation_uz', models.TextField(blank=True, null=True)),
                ('obligation_ru', models.TextField(blank=True, null=True)),
                ('obligation_en', models.TextField(blank=True, null=True)),
                ('obligation_oz', models.TextField(blank=True, null=True)),
                ('obligation_qr', models.TextField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('position_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('position_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('position_en', models.CharField(blank=True, max_length=255, null=True)),
                ('position_oz', models.CharField(blank=True, max_length=255, null=True)),
                ('position_qr', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(upload_to='staff_images/')),
                ('thumb', models.ImageField(upload_to='staff_images/thumb/')),
                ('reception_days', models.CharField(blank=True, max_length=255, null=True)),
                ('reception_days_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('reception_days_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('reception_days_en', models.CharField(blank=True, max_length=255, null=True)),
                ('reception_days_oz', models.CharField(blank=True, max_length=255, null=True)),
                ('reception_days_qr', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('inner_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.SmallIntegerField(choices=[(0, 'Minister'), (1, 'Deputy minister'), (2, 'Assistant of the minister'), (3, 'Advisor of the minister'), (4, 'International advisor of the minister'), (5, 'Scientific secretary')])),
                ('management_reception_days', models.CharField(blank=True, max_length=255, null=True)),
                ('management_reception_days_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('management_reception_days_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('management_reception_days_en', models.CharField(blank=True, max_length=255, null=True)),
                ('management_reception_days_oz', models.CharField(blank=True, max_length=255, null=True)),
                ('management_reception_days_qr', models.CharField(blank=True, max_length=255, null=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='structure.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_oz', models.CharField(max_length=255, null=True)),
                ('title_qr', models.CharField(max_length=255, null=True)),
                ('boss', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_boss', to='structure.staff')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divisions', to='structure.department')),
                ('staffs', models.ManyToManyField(blank=True, to='structure.Staff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='department',
            name='boss',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_boss', to='structure.staff'),
        ),
        migrations.AddField(
            model_name='department',
            name='region',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.region'),
        ),
        migrations.AddField(
            model_name='department',
            name='staffs',
            field=models.ManyToManyField(blank=True, to='structure.Staff'),
        ),
    ]
