# Generated by Django 3.2.7 on 2021-10-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_auto_20211007_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
