# Generated by Django 3.2.7 on 2021-10-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_auto_20211007_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Minister'), (2, 'Deputy minister'), (3, 'Assistant of the minister'), (4, 'Advisor of the minister'), (5, 'International advisor of the minister'), (6, 'Scientific secretary')]),
        ),
    ]
