# Generated by Django 3.2.7 on 2021-10-08 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_alter_management_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='thumb',
        ),
    ]
