# Generated by Django 3.2.7 on 2021-10-09 12:53

import autoslug.fields
from django.db import migrations
import structure.models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0006_remove_staff_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='', editable=False, max_length=255, populate_from=structure.models.Department.get_populate, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='division',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='', editable=False, max_length=255, populate_from=structure.models.Division.get_populate, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='management',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='', editable=False, max_length=255, populate_from=structure.models.Management.get_populate, unique=True),
            preserve_default=False,
        ),
    ]
