# Generated by Django 3.2.7 on 2021-10-12 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_interactiveservice_url'),
        ('structure', '0010_innovationcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovationcenter',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='innovation_centers', to='common.region'),
        ),
    ]
