# Generated by Django 3.2.7 on 2021-10-12 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_interactiveservice_url'),
        ('structure', '0011_innovationcenter_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovationcenter',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='innovation_centers', to='common.district'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='innovationcenter',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='innovation_centers', to='common.region'),
            preserve_default=False,
        ),
    ]
