# Generated by Django 3.2.7 on 2021-10-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0013_auto_20211013_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='innovationcenter',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='department',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='division',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='innovationcenter',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='organization',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
