# Generated by Django 3.2.7 on 2021-10-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0014_auto_20211018_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='staff',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
