# Generated by Django 3.2.7 on 2021-10-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0015_auto_20211018_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='activity',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='activity_en',
            new_name='about_en',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='activity_oz',
            new_name='about_oz',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='activity_qr',
            new_name='about_qr',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='activity_ru',
            new_name='about_ru',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='activity_uz',
            new_name='about_uz',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='works',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='works_en',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='works_oz',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='works_qr',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='works_ru',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='works_uz',
        ),
    ]
