# Generated by Django 3.2.7 on 2021-10-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0019_innovationterritory'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovationterritory',
            name='address_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='innovationterritory',
            name='address_oz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='innovationterritory',
            name='address_qr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='innovationterritory',
            name='address_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='innovationterritory',
            name='address_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='innovationterritory',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='innovationterritory',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='innovationterritory',
            name='content_oz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='innovationterritory',
            name='content_qr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='innovationterritory',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='innovationterritory',
            name='content_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='innovationterritory',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='innovationterritory',
            name='title_oz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='innovationterritory',
            name='title_qr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='innovationterritory',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='innovationterritory',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
