# Generated by Django 3.2.7 on 2021-10-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0019_auto_20211030_1412'),
        ('structure', '0022_innovationterritory_year'),
    ]

    operations = [
    ]
