# Generated by Django 3.2.7 on 2021-10-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0023_alter_innovationterritory_photo'),
        ('structure', '0023_merge_20211030_1414'),
    ]

    operations = [
    ]
