# Generated by Django 3.2.7 on 2021-11-08 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0024_merge_20211030_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentStaffsWithOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.department')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.staff')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='staffs',
            field=models.ManyToManyField(blank=True, related_name='department_staffs', through='structure.DepartmentStaffsWithOrder', to='structure.Staff'),
        ),
    ]
