# Generated by Django 3.2.7 on 2021-11-08 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0025_auto_20211108_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_boss', to='structure.staff'),
        ),
    ]
