# Generated by Django 3.2.7 on 2021-11-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0026_alter_organization_boss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='web',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
