# Generated by Django 3.2.7 on 2021-11-15 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_innovationidea'),
        ('structure', '0027_alter_organization_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovationterritory',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='innovation_territory', to='common.district'),
        ),
        migrations.AlterField(
            model_name='innovationterritory',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='innovation_territory', to='common.region'),
        ),
    ]
