# Generated by Django 3.2.7 on 2021-12-01 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0030_auto_20211127_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={},
        ),
    ]
