# Generated by Django 3.2.7 on 2021-12-01 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0032_auto_20211201_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentstaffswithorder',
            options={},
        ),
    ]
