# Generated by Django 3.2.7 on 2021-12-08 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0033_alter_departmentstaffswithorder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='boss',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.staff'),
        ),
        migrations.AlterField(
            model_name='department',
            name='staffs',
            field=models.ManyToManyField(blank=True, related_name='departments', through='structure.DepartmentStaffsWithOrder', to='structure.Staff'),
        ),
    ]
