# Generated by Django 3.2.7 on 2021-12-09 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0036_mininstrycouncil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mininstrycouncil',
            options={'verbose_name_plural': 'Ministry Council'},
        ),
    ]
