# Generated by Django 3.2.7 on 2023-03-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0037_alter_mininstrycouncil_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Director'), (2, 'Deputy minister'), (3, 'Assistant of the minister'), (4, 'Advisor of the minister'), (5, 'International advisor of the minister'), (6, 'Scientific secretary')]),
        ),
    ]
