# Generated by Django 3.2.7 on 2021-10-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211011_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[(1, 'Male'), (2, 'Female')], default=1, max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'Moderator'), (3, 'User')], default=3, max_length=255),
        ),
    ]
