# Generated by Django 3.2.7 on 2021-11-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, error_messages={'unique': 'User with that phone already exists'}, max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Moderator', 'Moderator'), ('Moderator2', 'Moderator2'), ('Moderator3', 'Moderator3'), ('User', 'User')], default='User', max_length=30),
        ),
    ]
