# Generated by Django 3.2.7 on 2021-11-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20211124_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, error_messages={'unique': 'User with that phone already exists'}, max_length=20, null=True, unique=True),
        ),
    ]
