# Generated by Django 3.2.7 on 2021-10-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210929_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='group',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
