# Generated by Django 3.2.7 on 2021-11-01 10:00

import autoslug.fields
from django.db import migrations
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menu_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=255, null=True, populate_from=menu.models.Menu.get_populate, unique=True),
        ),
    ]
