# Generated by Django 3.2.7 on 2021-11-02 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menu_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={},
        ),
        migrations.CreateModel(
            name='MenuImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(upload_to='menu_images/')),
                ('is_active', models.BooleanField(default=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='menu.menu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='menu_attachments/')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=150, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=150, null=True)),
                ('title_en', models.CharField(blank=True, max_length=150, null=True)),
                ('title_oz', models.CharField(blank=True, max_length=150, null=True)),
                ('title_qr', models.CharField(blank=True, max_length=150, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='menu.menu')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
