# Generated by Django 3.2.7 on 2021-11-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20211102_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuimage',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='menuimage',
            name='order',
            field=models.SmallIntegerField(default=1),
        ),
    ]
