# Generated by Django 3.2.7 on 2021-11-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proofreading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_full_name', models.CharField(max_length=255)),
                ('author_phone', models.CharField(max_length=20)),
                ('author_workplace', models.CharField(blank=True, max_length=255, null=True)),
                ('author_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('language', models.SmallIntegerField(blank=True, choices=[(1, 'British'), (2, 'American')], null=True)),
                ('article_name', models.CharField(max_length=255)),
                ('journal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('author_comment', models.TextField()),
                ('file', models.FileField(upload_to='proofreading_attachments/')),
                ('other_files', models.FileField(upload_to='proofreading_other_attachments')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
