# Generated by Django 3.2.7 on 2021-11-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofreading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofreading',
            name='other_files',
            field=models.FileField(blank=True, null=True, upload_to='proofreading_other_attachments'),
        ),
    ]
