# Generated by Django 3.2.7 on 2021-11-26 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proofreading', '0002_alter_proofreading_other_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofreading',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
