# Generated by Django 3.2.7 on 2021-11-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofreading', '0003_alter_proofreading_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofreading',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
